<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>alicia_d_driver</name>
  <version>0.0.1</version>
  <description>ROS 2 control hardware interface for the Alicia D arm.</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Hardware interface dependencies -->
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rcpputils</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>serial_driver</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  
  <!-- System dependencies -->
  <depend>libserial-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/alicia_d_driver.xml"/>
  </export>
</package>